GET http://localhost:3000/country

###

GET http://localhost:3000/city

###
POST  http://localhost:3000/city
Content-Type: application/json

{
    "id": 1,
    "stadname": "Borås",
    "countryid": 1,
    "population": 1538517
}